### ISSUE TITLE
How to connect to it using SQLPlus in the docker itself?

### ISSUE THREAD

**Issue by Freemason-12** [steveswinsburg/oracle19c-docker#5]
I created the default docker image with default parameters that you specified. But i have no idea on how to connect to it via sqlplus on a docker image itself:
I tried:
`sudo docker exec -ti oracle19c sqlplus /nolog`

then I got:
`SQL*Plus: Release 19.0.0.0.0 - Production on Sat May 7 12:27:29 2022`
`Version 19.3.0.0.0`

`Copyright (c) 1982, 2019, Oracle.  All rights reserved.`

`SQL> `

Then I entered:
`connect sys as sysdba`

And I got this error:
`ORA-12162: TNS:net service name is incorrectly specified`

What can I do?

**Comment by steveswinsburg** [comment]
Hi @Freemason-12, the defaults specify the service name as `orcl` so you'll need to connect like this:
`connect sys/password@orcl as sysdba`

**Comment by steveswinsburg** [comment]
I've updated the README. Cheers.
https://github.com/steveswinsburg/oracle19c-docker/blob/master/README.md

**Comment by Freemason-12** [comment]
Thank you. It worked as expected
