### ISSUE TITLE
Error sqlplus

### ISSUE THREAD

**Issue by doansangg** [steveswinsburg/oracle19c-docker#6]
![image](https://user-images.githubusercontent.com/54463985/192086015-668f4279-1347-446c-8881-870de20ce4d8.png)
SQL> connect sys/123@117.4.247.68:10622/camai
ERROR:
ORA-12543: TNS:destination host unreachable

SQL>  connect sys/123@117.4.247.68:10622/ORCLDB
ERROR:
ORA-12543: TNS:destination host unreachable

SQL> connect sys/123@117.4.247.68:10622/orcl as sysdba
ERROR:
ORA-12543: TNS:destination host unreachable

**Comment by steveswinsburg** [comment]
Are you trying to connect to a remote computer? Sounds like the remote machine is not available. Can you telnet to that host and port? Might need to open firewall rules etc.
