### ISSUE TITLE
FAILED CONNECTION ON INTELLIJ IDEA

### ISSUE THREAD

**Issue by mullatoes** [steveswinsburg/oracle19c-docker#8]
Installed my docker Oracle container and it runs successfully. The challenge is connecting it to database tools for query purposes.

Used this command... --name oracle19c \
-p 1521:1521 \
-p 5500:5500 \
-e ORACLE_PDB=bencon \
-e ORACLE_PWD=admin@123 \
-e INIT_SGA_SIZE=6000 \
-e INIT_PGA_SIZE=2000 \
-c 4 \
-d \
oracle/database:19.3.0-ee
...
<img width="912" alt="Screenshot 2024-04-01 at 01 15 12" src="https://github.com/steveswinsburg/oracle19c-docker/assets/127447524/67328e5e-b7b4-4a6c-b655-90a30100079e">
... What could be wrong?

**Comment by steveswinsburg** [comment]
Connecting as sys requires the sysdba privilege to be sent, so you normally connect with user name 'sys as sysdba'.
Can you connect via SQL developer and then translate those connection settings across to IntelliJ IDEA? Or is there a setting in there to tell it to use that elevated role?

**Comment by mullatoes** [comment]
Thanks @steveswinsburg . It has worked.
